#!/bin/sh

# Run latex and bibtex
latex levmarq.tex
bibtex levmarq.tex
latex levmarq.tex

# Generate PDF file
dvipdf levmarq.dvi levmarq.pdf

# Run latex2html
latex2html levmarq.tex

# copy navigation icons
/bin/cp -f contents.png next_g.png next.png prev_g.png prev.png up_g.png up.png levmarq

lst=`echo levmarq/node*.html levmarq/index.html levmarq/levmarq.html`

for x in `echo $lst`
do
  	if sed -e 's@file:/usr/share/latex2html/icons/\([a-z_]*\).png@\1.png@g' $x > /tmp/rgb42hj; then
        /bin/mv /tmp/rgb42hj $x
	else
	/bin/rm /tmp/rgb42hj
	fi
done
