#!/bin/sh
# $Id$

echo "Ravl Installation script."


if [ -z "$2" ] ; then
  INSTMODE=full
else
  INSTMODE=$2
fi


BUILDTYPE=fullbuild

case ${INSTMODE} in 
  full | auto)
     BUILDDIR=$1 
     if [ -z "$3" ] ; then
       CONFIGFILE=""
     else
       CONFIGFILE="CONFIGFILE=$3"
     fi
     if [ -z "$4" ] ; then
       TARGETARC=""
     else
       TARGETARC="ARC=$4"
     fi
     true ;;
  --config)
     BUILDDIR=$1
     CONFIGFILE="CONFIGFILE=$3"
     true ;;
  rpm)
     BUILDDIR=$3
     BUILDTYPE=rpmbuild
     true ;;
  *) echo "Unrecognised mode '${INSTMODE}'"
     INSTMODE=""
esac

if [ -z "$1" -o -z "${INSTMODE}" ]  ; then
  echo "Usage: install <target directory> [ mode [ config_file [ platform ] ] ]  "
    echo "Mode = ( full | auto | --config | rpm ) " 
  exit 1
fi

##################################
# Check perl
if which perl > /dev/null ; then
  true
else
  echo "Error:Can't find perl, this is required for installation & usage. "
  exit 1
fi

##################################
# Check make
make=""
if which make > /dev/null ; then
  if make -v 2>&1 | grep GNU > /dev/null  ; then
     MAKE=make
  fi
fi
if [ -z "${MAKE}" ] ; then
  if which gmake > /dev/null ; then 
    if gmake -v 2>&1 | grep GNU > /dev/null ; then
       MAKE=gmake
    fi
  fi
fi
if [ -z "${MAKE}" ] ; then
  echo "Error:Can't find GNU make, this is required for installation & usage. "
  exit
fi
echo "Make: ${MAKE} "

###################################
# Start installation

INSTALL_SITE="$1"
echo "Installation site '${INSTALL_SITE}'"
if mkdir -p ${INSTALL_SITE} ; then 
  true
else
  echo "Error: Can't create installation directory ${INSTALL_SITE}. " 
  exit 1
fi
ARC=`./QMake/config.arc`
if [ "${ARC}" = "unknown" ] ; then
  echo "Warning: Unknown architecture. " 
  echo "This may not work, but we'll try anyway. "
fi
echo "Architecture: '${ARC}'"

# Install make system.
if ${MAKE} -C QMake -f ./QMake.mk MAKEHOME=`pwd`/QMake BASEINSTALL=1 PROJECT_OUT=${INSTALL_SITE} BUILD_TAG= ROOTDIR=${BUILDDIR} PROCS=1 FULLBUILDSRC='BASE_VAR=none' ${CONFIGFILE} ; then
  true
else
  echo "ERROR: Failed to install make system. "
  echo "Aborting installation. "
  exit 1
fi

# Compile libraries
if ${MAKE} -f ${BUILDDIR}/share/RAVL/QMake/QMake.mk MAKEHOME=${BUILDDIR}/share/RAVL/QMake BASEINSTALL=1 INSTALLHOME=${BUILDDIR} PROJECT_OUT=${INSTALL_SITE} BUILD_TAG= ROOTDIR=${BUILDDIR} ${BUILDTYPE} ${TARGETARC} FULLBUILDSRC='BASE_VAR=none' INCLUDEDIR=${BUILDDIR}/include/Ravl; then 
  true
else
  echo "ERROR: Failed to build libraries. "
  echo "Aborting installation. "
  exit 1
fi

echo "\nInstallation was successful.\n"

echo "Refer to file:$RAVL_INSTALLATION/RavlProject/share/doc/RAVL/Auto/Basic/Tree/Ravl.Installation.html#USAGE for usage."

exit 0
