$(FileObject:lib)$(FilePattern:%.mak)


#--------------------------
# Compiler and flags etc
#--------------------------
CC = cl.exe

LD = lib.exe

INCLUDES =  /I "include\Win32" /I "include" /I "c:/Program Files/Microsoft Visual Studio 8/VC/ATLMFC/INCLUDE" /I "c:/Program Files/Microsoft Visual Studio 8/VC/INCLUDE" /I "c:/Program Files/Microsoft Visual Studio 8/VC/PlatformSDK/include" /I "c:/Program Files/Microsoft Visual Studio 8/SDK/v2.0/include" $(NMakeExtraInclude)

DEFINES = /D "NDEBUG" /D "_LIB" /D "VISUAL_CPP" /D "WIN32" /D "RAVL_USE_GTK2=1" /D "_CRT_SECURE_NO_DEPRECATE" /D "_SCL_SECURE_NO_DEPRECATE" /D "_SCL_SECURE=0" /D "_UNICODE" /D "UNICODE"


OPTFLAGS = /nologo /c /O2 /Ob1 /EHsc /MD /TP

DEBUGFLAGS = /nologo /c /Ob1 /EHsc /MD /TP

#-----------------------------------------------------------------------------
# OK lets define some of our output directories and define script to make them
#-----------------------------------------------------------------------------
DEBUGOBJDIR = $(ProjectOut)/win32/debug/obj/$(libname)
DEBUGLIBDIR = $(ProjectOut)/win32/debug/lib

OPTOBJDIR = $(ProjectOut)/win32/opt/obj/$(libname)
OPTLIBDIR = $(ProjectOut)/win32/opt/lib


opt:: setup $(forall:sources: $$(OPTOBJDIR)/$(objectfile:$(filename)))
	@echo -- making $$(OPTLIBDIR)/$(libname).lib
	$$(LD) /NOLOGO /out:$$(OPTLIBDIR)/$(libname).lib $$(OPTOBJDIR)/*.obj


debug:: setup $(forall:sources: $$(DEBUGOBJDIR)/$(objectfile:$(filename))) 
	@echo -- making $$(DEBUGLIBDIR)/$(libname).lib
	$$(LD) /NOLOGO /out:$$(DEBUGLIBDIR)/$(libname).lib $$(DEBUGOBJDIR)/*.obj

setup::
        echo --- creating dir for $(libname)
        @if not exist "$$(DEBUGOBJDIR)" mkdir "$$(DEBUGOBJDIR)"
        @if not exist "$$(DEBUGLIBDIR)" mkdir "$$(DEBUGLIBDIR)"
        @if not exist "$$(OPTOBJDIR)" mkdir "$$(OPTOBJDIR)"
        @if not exist "$$(OPTLIBDIR)" mkdir "$$(OPTLIBDIR)"


$(forall:sources:
$$(OPTOBJDIR)/$(objectfile:$$(OPTOBJDIR)/$(filename) ): ../$(filename) 
        $$(CC) $$(INCLUDES) $$(DEFINES) $$(OPTFLAGS) /Fo$$(OPTOBJDIR)/$(filebasename:$(filename)).obj ../$(filename)

$$(DEBUGOBJDIR)/$(objectfile:$$(DEBUGOBJDIR)/$(filename) ): ../$(filename) 
        $$(CC) $$(INCLUDES) $$(DEFINES) $$(OPTFLAGS) /Fo$$(DEBUGOBJDIR)/$(filebasename:$(filename)).obj ../$(filename)
)

