# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

"""
Recognition and Vision Library
RAVL provides a base C++ class library together with a range of
computer vision, pattern recognition and supporting tools.
"""

import _Ravl
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class DListRealC(_object):
    """Proxy of C++ DListRealC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListRealC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListRealC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListRealC"""
        this = _Ravl.new_DListRealC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListRealC_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListRealC_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListRealC_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> double"""
        return _Ravl.DListRealC_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> double"""
        return _Ravl.DListRealC_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListRealC_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListRealC_MoveLast(*args)

    def First(*args):
        """First(self) -> double"""
        return _Ravl.DListRealC_First(*args)

    def Last(*args):
        """Last(self) -> double"""
        return _Ravl.DListRealC_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListRealC_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListRealC_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> double"""
        return _Ravl.DListRealC_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListRealC
    __del__ = lambda self : None;
DListRealC_swigregister = _Ravl.DListRealC_swigregister
DListRealC_swigregister(DListRealC)

class DListRealIterC(_object):
    """Proxy of C++ DListRealIterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListRealIterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListRealIterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListRealIterC
        __init__(self, lst) -> DListRealIterC
        """
        this = _Ravl.new_DListRealIterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListRealIterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListRealIterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListRealIterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListRealIterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListRealIterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListRealIterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListRealIterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListRealIterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListRealIterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListRealIterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListRealIterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> double"""
        return _Ravl.DListRealIterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> double"""
        return _Ravl.DListRealIterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> double"""
        return _Ravl.DListRealIterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> double"""
        return _Ravl.DListRealIterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListRealC"""
        return _Ravl.DListRealIterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListRealC"""
        return _Ravl.DListRealIterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListRealC"""
        return _Ravl.DListRealIterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListRealC"""
        return _Ravl.DListRealIterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> double"""
        return _Ravl.DListRealIterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> double"""
        return _Ravl.DListRealIterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListRealIterC
    __del__ = lambda self : None;
DListRealIterC_swigregister = _Ravl.DListRealIterC_swigregister
DListRealIterC_swigregister(DListRealIterC)

class DListIntC(_object):
    """Proxy of C++ DListIntC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListIntC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListIntC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListIntC"""
        this = _Ravl.new_DListIntC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListIntC_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListIntC_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListIntC_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> int"""
        return _Ravl.DListIntC_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> int"""
        return _Ravl.DListIntC_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListIntC_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListIntC_MoveLast(*args)

    def First(*args):
        """First(self) -> int"""
        return _Ravl.DListIntC_First(*args)

    def Last(*args):
        """Last(self) -> int"""
        return _Ravl.DListIntC_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListIntC_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListIntC_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> int"""
        return _Ravl.DListIntC_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListIntC
    __del__ = lambda self : None;
DListIntC_swigregister = _Ravl.DListIntC_swigregister
DListIntC_swigregister(DListIntC)

class DListIntIterC(_object):
    """Proxy of C++ DListIntIterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListIntIterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListIntIterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListIntIterC
        __init__(self, lst) -> DListIntIterC
        """
        this = _Ravl.new_DListIntIterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListIntIterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListIntIterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListIntIterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListIntIterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListIntIterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListIntIterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListIntIterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListIntIterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListIntIterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListIntIterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListIntIterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> int"""
        return _Ravl.DListIntIterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> int"""
        return _Ravl.DListIntIterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> int"""
        return _Ravl.DListIntIterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> int"""
        return _Ravl.DListIntIterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListIntC"""
        return _Ravl.DListIntIterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListIntC"""
        return _Ravl.DListIntIterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListIntC"""
        return _Ravl.DListIntIterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListIntC"""
        return _Ravl.DListIntIterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> int"""
        return _Ravl.DListIntIterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> int"""
        return _Ravl.DListIntIterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListIntIterC
    __del__ = lambda self : None;
DListIntIterC_swigregister = _Ravl.DListIntIterC_swigregister
DListIntIterC_swigregister(DListIntIterC)

class DListUIntC(_object):
    """Proxy of C++ DListUIntC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListUIntC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListUIntC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListUIntC"""
        this = _Ravl.new_DListUIntC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListUIntC_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListUIntC_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListUIntC_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> unsigned int"""
        return _Ravl.DListUIntC_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> unsigned int"""
        return _Ravl.DListUIntC_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListUIntC_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListUIntC_MoveLast(*args)

    def First(*args):
        """First(self) -> unsigned int"""
        return _Ravl.DListUIntC_First(*args)

    def Last(*args):
        """Last(self) -> unsigned int"""
        return _Ravl.DListUIntC_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListUIntC_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListUIntC_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> unsigned int"""
        return _Ravl.DListUIntC_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListUIntC
    __del__ = lambda self : None;
DListUIntC_swigregister = _Ravl.DListUIntC_swigregister
DListUIntC_swigregister(DListUIntC)

class DListUIntIterC(_object):
    """Proxy of C++ DListUIntIterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListUIntIterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListUIntIterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListUIntIterC
        __init__(self, lst) -> DListUIntIterC
        """
        this = _Ravl.new_DListUIntIterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListUIntIterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListUIntIterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListUIntIterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListUIntIterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListUIntIterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListUIntIterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListUIntIterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListUIntIterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListUIntIterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListUIntIterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListUIntIterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> unsigned int"""
        return _Ravl.DListUIntIterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> unsigned int"""
        return _Ravl.DListUIntIterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> unsigned int"""
        return _Ravl.DListUIntIterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> unsigned int"""
        return _Ravl.DListUIntIterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListUIntC"""
        return _Ravl.DListUIntIterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListUIntC"""
        return _Ravl.DListUIntIterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListUIntC"""
        return _Ravl.DListUIntIterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListUIntC"""
        return _Ravl.DListUIntIterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> unsigned int"""
        return _Ravl.DListUIntIterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> unsigned int"""
        return _Ravl.DListUIntIterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListUIntIterC
    __del__ = lambda self : None;
DListUIntIterC_swigregister = _Ravl.DListUIntIterC_swigregister
DListUIntIterC_swigregister(DListUIntIterC)

class DListInt64C(_object):
    """Proxy of C++ DListInt64C class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListInt64C, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListInt64C, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListInt64C"""
        this = _Ravl.new_DListInt64C(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListInt64C_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListInt64C_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListInt64C_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> long long"""
        return _Ravl.DListInt64C_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> long long"""
        return _Ravl.DListInt64C_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListInt64C_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListInt64C_MoveLast(*args)

    def First(*args):
        """First(self) -> long long"""
        return _Ravl.DListInt64C_First(*args)

    def Last(*args):
        """Last(self) -> long long"""
        return _Ravl.DListInt64C_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListInt64C_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListInt64C_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> long long"""
        return _Ravl.DListInt64C_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListInt64C
    __del__ = lambda self : None;
DListInt64C_swigregister = _Ravl.DListInt64C_swigregister
DListInt64C_swigregister(DListInt64C)

class DListInt64IterC(_object):
    """Proxy of C++ DListInt64IterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListInt64IterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListInt64IterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListInt64IterC
        __init__(self, lst) -> DListInt64IterC
        """
        this = _Ravl.new_DListInt64IterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListInt64IterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListInt64IterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListInt64IterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListInt64IterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListInt64IterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListInt64IterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListInt64IterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListInt64IterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListInt64IterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListInt64IterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListInt64IterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> long long"""
        return _Ravl.DListInt64IterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> long long"""
        return _Ravl.DListInt64IterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> long long"""
        return _Ravl.DListInt64IterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> long long"""
        return _Ravl.DListInt64IterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListInt64C"""
        return _Ravl.DListInt64IterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListInt64C"""
        return _Ravl.DListInt64IterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListInt64C"""
        return _Ravl.DListInt64IterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListInt64C"""
        return _Ravl.DListInt64IterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> long long"""
        return _Ravl.DListInt64IterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> long long"""
        return _Ravl.DListInt64IterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListInt64IterC
    __del__ = lambda self : None;
DListInt64IterC_swigregister = _Ravl.DListInt64IterC_swigregister
DListInt64IterC_swigregister(DListInt64IterC)

class DListInt16C(_object):
    """Proxy of C++ DListInt16C class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListInt16C, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListInt16C, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListInt16C"""
        this = _Ravl.new_DListInt16C(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListInt16C_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListInt16C_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListInt16C_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> short"""
        return _Ravl.DListInt16C_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> short"""
        return _Ravl.DListInt16C_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListInt16C_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListInt16C_MoveLast(*args)

    def First(*args):
        """First(self) -> short"""
        return _Ravl.DListInt16C_First(*args)

    def Last(*args):
        """Last(self) -> short"""
        return _Ravl.DListInt16C_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListInt16C_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListInt16C_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> short"""
        return _Ravl.DListInt16C_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListInt16C
    __del__ = lambda self : None;
DListInt16C_swigregister = _Ravl.DListInt16C_swigregister
DListInt16C_swigregister(DListInt16C)

class DListInt16IterC(_object):
    """Proxy of C++ DListInt16IterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListInt16IterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListInt16IterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListInt16IterC
        __init__(self, lst) -> DListInt16IterC
        """
        this = _Ravl.new_DListInt16IterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListInt16IterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListInt16IterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListInt16IterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListInt16IterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListInt16IterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListInt16IterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListInt16IterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListInt16IterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListInt16IterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListInt16IterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListInt16IterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> short"""
        return _Ravl.DListInt16IterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> short"""
        return _Ravl.DListInt16IterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> short"""
        return _Ravl.DListInt16IterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> short"""
        return _Ravl.DListInt16IterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListInt16C"""
        return _Ravl.DListInt16IterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListInt16C"""
        return _Ravl.DListInt16IterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListInt16C"""
        return _Ravl.DListInt16IterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListInt16C"""
        return _Ravl.DListInt16IterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> short"""
        return _Ravl.DListInt16IterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> short"""
        return _Ravl.DListInt16IterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListInt16IterC
    __del__ = lambda self : None;
DListInt16IterC_swigregister = _Ravl.DListInt16IterC_swigregister
DListInt16IterC_swigregister(DListInt16IterC)

class DListByteC(_object):
    """Proxy of C++ DListByteC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListByteC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListByteC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListByteC"""
        this = _Ravl.new_DListByteC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListByteC_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListByteC_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListByteC_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> unsigned char"""
        return _Ravl.DListByteC_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> unsigned char"""
        return _Ravl.DListByteC_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListByteC_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListByteC_MoveLast(*args)

    def First(*args):
        """First(self) -> unsigned char"""
        return _Ravl.DListByteC_First(*args)

    def Last(*args):
        """Last(self) -> unsigned char"""
        return _Ravl.DListByteC_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListByteC_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListByteC_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> unsigned char"""
        return _Ravl.DListByteC_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListByteC
    __del__ = lambda self : None;
DListByteC_swigregister = _Ravl.DListByteC_swigregister
DListByteC_swigregister(DListByteC)

class DListByteIterC(_object):
    """Proxy of C++ DListByteIterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListByteIterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListByteIterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListByteIterC
        __init__(self, lst) -> DListByteIterC
        """
        this = _Ravl.new_DListByteIterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListByteIterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListByteIterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListByteIterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListByteIterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListByteIterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListByteIterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListByteIterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListByteIterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListByteIterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListByteIterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListByteIterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> unsigned char"""
        return _Ravl.DListByteIterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> unsigned char"""
        return _Ravl.DListByteIterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> unsigned char"""
        return _Ravl.DListByteIterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> unsigned char"""
        return _Ravl.DListByteIterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListByteC"""
        return _Ravl.DListByteIterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListByteC"""
        return _Ravl.DListByteIterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListByteC"""
        return _Ravl.DListByteIterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListByteC"""
        return _Ravl.DListByteIterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> unsigned char"""
        return _Ravl.DListByteIterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> unsigned char"""
        return _Ravl.DListByteIterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListByteIterC
    __del__ = lambda self : None;
DListByteIterC_swigregister = _Ravl.DListByteIterC_swigregister
DListByteIterC_swigregister(DListByteIterC)

class Point2dC(_object):
    """Proxy of C++ Point2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Point2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Point2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Point2dC
        __init__(self, x, y) -> Point2dC
        """
        this = _Ravl.new_Point2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Row(*args):
        """Row(self) -> RealT"""
        return _Ravl.Point2dC_Row(*args)

    def Col(*args):
        """Col(self) -> RealT"""
        return _Ravl.Point2dC_Col(*args)

    __swig_destroy__ = _Ravl.delete_Point2dC
    __del__ = lambda self : None;
Point2dC_swigregister = _Ravl.Point2dC_swigregister
Point2dC_swigregister(Point2dC)

class DListPoint2dC(_object):
    """Proxy of C++ DListPoint2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListPoint2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListPoint2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> DListPoint2dC"""
        this = _Ravl.new_DListPoint2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Empty(*args):
        """Empty(self)"""
        return _Ravl.DListPoint2dC_Empty(*args)

    def InsFirst(*args):
        """InsFirst(self, dat)"""
        return _Ravl.DListPoint2dC_InsFirst(*args)

    def InsLast(*args):
        """InsLast(self, dat)"""
        return _Ravl.DListPoint2dC_InsLast(*args)

    def PopFirst(*args):
        """PopFirst(self) -> Point2dC"""
        return _Ravl.DListPoint2dC_PopFirst(*args)

    def PopLast(*args):
        """PopLast(self) -> Point2dC"""
        return _Ravl.DListPoint2dC_PopLast(*args)

    def MoveFirst(*args):
        """MoveFirst(self, lst)"""
        return _Ravl.DListPoint2dC_MoveFirst(*args)

    def MoveLast(*args):
        """MoveLast(self, lst)"""
        return _Ravl.DListPoint2dC_MoveLast(*args)

    def First(*args):
        """First(self) -> Point2dC"""
        return _Ravl.DListPoint2dC_First(*args)

    def Last(*args):
        """Last(self) -> Point2dC"""
        return _Ravl.DListPoint2dC_Last(*args)

    def Del(*args):
        """Del(self, x) -> bool"""
        return _Ravl.DListPoint2dC_Del(*args)

    def Contains(*args):
        """Contains(self, x) -> bool"""
        return _Ravl.DListPoint2dC_Contains(*args)

    def Nth(*args):
        """Nth(self, n) -> Point2dC"""
        return _Ravl.DListPoint2dC_Nth(*args)

    __swig_destroy__ = _Ravl.delete_DListPoint2dC
    __del__ = lambda self : None;
DListPoint2dC_swigregister = _Ravl.DListPoint2dC_swigregister
DListPoint2dC_swigregister(DListPoint2dC)

class DListPoint2dIterC(_object):
    """Proxy of C++ DListPoint2dIterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DListPoint2dIterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DListPoint2dIterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DListPoint2dIterC
        __init__(self, lst) -> DListPoint2dIterC
        """
        this = _Ravl.new_DListPoint2dIterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DListPoint2dIterC_IsValid(*args)

    def First(*args):
        """First(self)"""
        return _Ravl.DListPoint2dIterC_First(*args)

    def Last(*args):
        """Last(self)"""
        return _Ravl.DListPoint2dIterC_Last(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.DListPoint2dIterC_IsElm(*args)

    def IsFirst(*args):
        """IsFirst(self) -> bool"""
        return _Ravl.DListPoint2dIterC_IsFirst(*args)

    def IsLast(*args):
        """IsLast(self) -> bool"""
        return _Ravl.DListPoint2dIterC_IsLast(*args)

    def Next(*args):
        """Next(self)"""
        return _Ravl.DListPoint2dIterC_Next(*args)

    def Prev(*args):
        """Prev(self)"""
        return _Ravl.DListPoint2dIterC_Prev(*args)

    def NextCrc(*args):
        """NextCrc(self)"""
        return _Ravl.DListPoint2dIterC_NextCrc(*args)

    def PrevCrc(*args):
        """PrevCrc(self)"""
        return _Ravl.DListPoint2dIterC_PrevCrc(*args)

    def Nth(*args):
        """Nth(self, n)"""
        return _Ravl.DListPoint2dIterC_Nth(*args)

    def NextData(*args):
        """NextData(self) -> Point2dC"""
        return _Ravl.DListPoint2dIterC_NextData(*args)

    def PrevData(*args):
        """PrevData(self) -> Point2dC"""
        return _Ravl.DListPoint2dIterC_PrevData(*args)

    def NextCrcData(*args):
        """NextCrcData(self) -> Point2dC"""
        return _Ravl.DListPoint2dIterC_NextCrcData(*args)

    def PrevCrcData(*args):
        """PrevCrcData(self) -> Point2dC"""
        return _Ravl.DListPoint2dIterC_PrevCrcData(*args)

    def Tail(*args):
        """Tail(self) -> DListPoint2dC"""
        return _Ravl.DListPoint2dIterC_Tail(*args)

    def Head(*args):
        """Head(self) -> DListPoint2dC"""
        return _Ravl.DListPoint2dIterC_Head(*args)

    def InclusiveTail(*args):
        """InclusiveTail(self) -> DListPoint2dC"""
        return _Ravl.DListPoint2dIterC_InclusiveTail(*args)

    def InclusiveHead(*args):
        """InclusiveHead(self) -> DListPoint2dC"""
        return _Ravl.DListPoint2dIterC_InclusiveHead(*args)

    def Data(*args):
        """Data(self) -> Point2dC"""
        return _Ravl.DListPoint2dIterC_Data(*args)

    def __deref__(*args):
        """__deref__(self) -> Point2dC"""
        return _Ravl.DListPoint2dIterC___deref__(*args)

    __swig_destroy__ = _Ravl.delete_DListPoint2dIterC
    __del__ = lambda self : None;
    def Row(*args):
        """Row(self) -> RealT"""
        return _Ravl.DListPoint2dIterC_Row(*args)

    def Col(*args):
        """Col(self) -> RealT"""
        return _Ravl.DListPoint2dIterC_Col(*args)

DListPoint2dIterC_swigregister = _Ravl.DListPoint2dIterC_swigregister
DListPoint2dIterC_swigregister(DListPoint2dIterC)

class IndexC(_object):
    """Proxy of C++ IndexC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IndexC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IndexC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> IndexC
        __init__(self, ?) -> IndexC
        """
        this = _Ravl.new_IndexC(*args)
        try: self.this.append(this)
        except: self.this = this
    def V(*args):
        """V(self) -> IntT"""
        return _Ravl.IndexC_V(*args)

    __swig_destroy__ = _Ravl.delete_IndexC
    __del__ = lambda self : None;
IndexC_swigregister = _Ravl.IndexC_swigregister
IndexC_swigregister(IndexC)

def ToList(*args):
  """
    ToList(list) -> PyObject
    ToList(list) -> PyObject
    ToList(list) -> PyObject
    ToList(list) -> PyObject
    ToList(list) -> PyObject
    ToList(list) -> PyObject
    ToList(list) -> PyObject
    """
  return _Ravl.ToList(*args)

class Index2dC(_object):
    """Proxy of C++ Index2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Index2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Index2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Index2dC
        __init__(self, x, y) -> Index2dC
        __init__(self, x, y) -> Index2dC
        """
        this = _Ravl.new_Index2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Row(*args):
        """Row(self) -> IndexC"""
        return _Ravl.Index2dC_Row(*args)

    def Col(*args):
        """Col(self) -> IndexC"""
        return _Ravl.Index2dC_Col(*args)

    __swig_destroy__ = _Ravl.delete_Index2dC
    __del__ = lambda self : None;
Index2dC_swigregister = _Ravl.Index2dC_swigregister
Index2dC_swigregister(Index2dC)

class IndexRange2dC(_object):
    """Proxy of C++ IndexRange2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IndexRange2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IndexRange2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> IndexRange2dC"""
        this = _Ravl.new_IndexRange2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Rows(*args):
        """Rows(self) -> IntT"""
        return _Ravl.IndexRange2dC_Rows(*args)

    def Cols(*args):
        """Cols(self) -> IntT"""
        return _Ravl.IndexRange2dC_Cols(*args)

    def Area(*args):
        """Area(self) -> SizeT"""
        return _Ravl.IndexRange2dC_Area(*args)

    def Contains(*args):
        """Contains(self, index) -> bool"""
        return _Ravl.IndexRange2dC_Contains(*args)

    def Expand(*args):
        """Expand(self, n) -> IndexRange2dC"""
        return _Ravl.IndexRange2dC_Expand(*args)

    def ClipBy(*args):
        """ClipBy(self, range)"""
        return _Ravl.IndexRange2dC_ClipBy(*args)

    __swig_destroy__ = _Ravl.delete_IndexRange2dC
    __del__ = lambda self : None;
IndexRange2dC_swigregister = _Ravl.IndexRange2dC_swigregister
IndexRange2dC_swigregister(IndexRange2dC)

class Array2dByteC(_object):
    """Proxy of C++ Array2dByteC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Array2dByteC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Array2dByteC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Array2dByteC
        __init__(self, rows, cols) -> Array2dByteC
        __init__(self, range) -> Array2dByteC
        """
        this = _Ravl.new_Array2dByteC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Frame(*args):
        """Frame(self) -> IndexRange2dC"""
        return _Ravl.Array2dByteC_Frame(*args)

    def Fill(*args):
        """Fill(self, value)"""
        return _Ravl.Array2dByteC_Fill(*args)

    def Stride(*args):
        """Stride(self) -> IntT"""
        return _Ravl.Array2dByteC_Stride(*args)

    def Access(*args):
        """
        Access(self, index) -> unsigned char
        Access(self, r, c) -> unsigned char
        Access(self, r, c) -> unsigned char
        """
        return _Ravl.Array2dByteC_Access(*args)

    __swig_destroy__ = _Ravl.delete_Array2dByteC
    __del__ = lambda self : None;
Array2dByteC_swigregister = _Ravl.Array2dByteC_swigregister
Array2dByteC_swigregister(Array2dByteC)

class Array2dRealC(_object):
    """Proxy of C++ Array2dRealC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Array2dRealC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Array2dRealC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Array2dRealC
        __init__(self, rows, cols) -> Array2dRealC
        __init__(self, range) -> Array2dRealC
        """
        this = _Ravl.new_Array2dRealC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Frame(*args):
        """Frame(self) -> IndexRange2dC"""
        return _Ravl.Array2dRealC_Frame(*args)

    def Fill(*args):
        """Fill(self, value)"""
        return _Ravl.Array2dRealC_Fill(*args)

    def Stride(*args):
        """Stride(self) -> IntT"""
        return _Ravl.Array2dRealC_Stride(*args)

    def Access(*args):
        """
        Access(self, index) -> double
        Access(self, r, c) -> double
        Access(self, r, c) -> double
        """
        return _Ravl.Array2dRealC_Access(*args)

    __swig_destroy__ = _Ravl.delete_Array2dRealC
    __del__ = lambda self : None;
Array2dRealC_swigregister = _Ravl.Array2dRealC_swigregister
Array2dRealC_swigregister(Array2dRealC)

class StringC(_object):
    """Proxy of C++ StringC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> StringC
        __init__(self, ?) -> StringC
        """
        this = _Ravl.new_StringC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsEmpty(*args):
        """IsEmpty(self) -> bool"""
        return _Ravl.StringC_IsEmpty(*args)

    def chars(*args):
        """chars(self) -> char"""
        return _Ravl.StringC_chars(*args)

    def Size(*args):
        """Size(self) -> SizeT"""
        return _Ravl.StringC_Size(*args)

    def __str__(*args):
        """__str__(self) -> char"""
        return _Ravl.StringC___str__(*args)

    __swig_destroy__ = _Ravl.delete_StringC
    __del__ = lambda self : None;
StringC_swigregister = _Ravl.StringC_swigregister
StringC_swigregister(StringC)

class RealRangeC(_object):
    """Proxy of C++ RealRangeC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RealRangeC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RealRangeC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, size=0) -> RealRangeC
        __init__(self) -> RealRangeC
        __init__(self, minReal, maxReal) -> RealRangeC
        """
        this = _Ravl.new_RealRangeC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Size(*args):
        """Size(self) -> RealT"""
        return _Ravl.RealRangeC_Size(*args)

    def Range(*args):
        """Range(self) -> RealRangeC"""
        return _Ravl.RealRangeC_Range(*args)

    def Min(*args):
        """
        Min(self) -> RealT
        Min(self) -> RealT
        """
        return _Ravl.RealRangeC_Min(*args)

    def Max(*args):
        """
        Max(self) -> RealT
        Max(self) -> RealT
        """
        return _Ravl.RealRangeC_Max(*args)

    def Center(*args):
        """Center(self) -> RealT"""
        return _Ravl.RealRangeC_Center(*args)

    def CenterD(*args):
        """CenterD(self) -> RealT"""
        return _Ravl.RealRangeC_CenterD(*args)

    def Percentage(*args):
        """Percentage(self, p) -> RealT"""
        return _Ravl.RealRangeC_Percentage(*args)

    def IsEmpty(*args):
        """IsEmpty(self) -> bool"""
        return _Ravl.RealRangeC_IsEmpty(*args)

    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.RealRangeC_IsValid(*args)

    def Contains(*args):
        """
        Contains(self, i) -> bool
        Contains(self, range) -> bool
        """
        return _Ravl.RealRangeC_Contains(*args)

    def __eq__(*args):
        """__eq__(self, range) -> bool"""
        return _Ravl.RealRangeC___eq__(*args)

    def __ne__(*args):
        """__ne__(self, range) -> bool"""
        return _Ravl.RealRangeC___ne__(*args)

    def In(*args):
        """In(self, range) -> bool"""
        return _Ravl.RealRangeC_In(*args)

    def IsOverlapping(*args):
        """IsOverlapping(self, r) -> bool"""
        return _Ravl.RealRangeC_IsOverlapping(*args)

    def SetOrigin(*args):
        """SetOrigin(self, position) -> RealRangeC"""
        return _Ravl.RealRangeC_SetOrigin(*args)

    def __iadd__(*args):
        """__iadd__(self, i) -> RealRangeC"""
        return _Ravl.RealRangeC___iadd__(*args)

    def __isub__(*args):
        """__isub__(self, i) -> RealRangeC"""
        return _Ravl.RealRangeC___isub__(*args)

    def __add__(*args):
        """__add__(self, i) -> RealRangeC"""
        return _Ravl.RealRangeC___add__(*args)

    def __sub__(*args):
        """__sub__(self, i) -> RealRangeC"""
        return _Ravl.RealRangeC___sub__(*args)

    def ClipBy(*args):
        """ClipBy(self, r) -> RealRangeC"""
        return _Ravl.RealRangeC_ClipBy(*args)

    def Clip(*args):
        """Clip(self, r) -> RealT"""
        return _Ravl.RealRangeC_Clip(*args)

    def FirstHalf(*args):
        """FirstHalf(self) -> RealRangeC"""
        return _Ravl.RealRangeC_FirstHalf(*args)

    def FirstHalfD(*args):
        """FirstHalfD(self) -> RealRangeC"""
        return _Ravl.RealRangeC_FirstHalfD(*args)

    def Enlarge(*args):
        """Enlarge(self, f) -> RealRangeC"""
        return _Ravl.RealRangeC_Enlarge(*args)

    def Expand(*args):
        """Expand(self, n) -> RealRangeC"""
        return _Ravl.RealRangeC_Expand(*args)

    def Shrink(*args):
        """Shrink(self, n) -> RealRangeC"""
        return _Ravl.RealRangeC_Shrink(*args)

    def ShrinkHigh(*args):
        """ShrinkHigh(self, n) -> RealRangeC"""
        return _Ravl.RealRangeC_ShrinkHigh(*args)

    def Swap(*args):
        """Swap(self, r) -> RealRangeC"""
        return _Ravl.RealRangeC_Swap(*args)

    def Involve(*args):
        """
        Involve(self, i) -> RealRangeC
        Involve(self, subRange) -> RealRangeC
        """
        return _Ravl.RealRangeC_Involve(*args)

    __swig_destroy__ = _Ravl.delete_RealRangeC
    __del__ = lambda self : None;
RealRangeC_swigregister = _Ravl.RealRangeC_swigregister
RealRangeC_swigregister(RealRangeC)

def PrintIOFormats(*args):
  """
    PrintIOFormats(os=std::cout)
    PrintIOFormats()
    """
  return _Ravl.PrintIOFormats(*args)

def PrintIOConversions(*args):
  """
    PrintIOConversions(os=std::cout)
    PrintIOConversions()
    """
  return _Ravl.PrintIOConversions(*args)

def PrintIOClassTypes(*args):
  """
    PrintIOClassTypes(os=std::cout)
    PrintIOClassTypes()
    """
  return _Ravl.PrintIOClassTypes(*args)

class RealRange2dC(_object):
    """Proxy of C++ RealRange2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RealRange2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RealRange2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> RealRange2dC
        __init__(self, rowNumber, colNumber) -> RealRange2dC
        __init__(self, rowRange, colRange) -> RealRange2dC
        __init__(self, range) -> RealRange2dC
        __init__(self, minRow, maxRow, minCol, maxCol) -> RealRange2dC
        """
        this = _Ravl.new_RealRange2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def TRow(*args):
        """
        TRow(self) -> RealT
        TRow(self) -> RealT
        """
        return _Ravl.RealRange2dC_TRow(*args)

    def LCol(*args):
        """
        LCol(self) -> RealT
        LCol(self) -> RealT
        """
        return _Ravl.RealRange2dC_LCol(*args)

    def BRow(*args):
        """
        BRow(self) -> RealT
        BRow(self) -> RealT
        """
        return _Ravl.RealRange2dC_BRow(*args)

    def RCol(*args):
        """
        RCol(self) -> RealT
        RCol(self) -> RealT
        """
        return _Ravl.RealRange2dC_RCol(*args)

    def Rows(*args):
        """Rows(self) -> RealT"""
        return _Ravl.RealRange2dC_Rows(*args)

    def Cols(*args):
        """Cols(self) -> RealT"""
        return _Ravl.RealRange2dC_Cols(*args)

    def Area(*args):
        """Area(self) -> RealT"""
        return _Ravl.RealRange2dC_Area(*args)

    def Dilate(*args):
        """Dilate(self) -> RealRange2dC"""
        return _Ravl.RealRange2dC_Dilate(*args)

    def Erode(*args):
        """Erode(self) -> RealRange2dC"""
        return _Ravl.RealRange2dC_Erode(*args)

    def Expand(*args):
        """Expand(self, n) -> RealRange2dC"""
        return _Ravl.RealRange2dC_Expand(*args)

    def Shrink(*args):
        """Shrink(self, n) -> RealRange2dC"""
        return _Ravl.RealRange2dC_Shrink(*args)

    def ClipBy(*args):
        """ClipBy(self, r) -> RealRange2dC"""
        return _Ravl.RealRange2dC_ClipBy(*args)

    def Contains(*args):
        """Contains(self, oth) -> bool"""
        return _Ravl.RealRange2dC_Contains(*args)

    def RowRange(*args):
        """RowRange(self) -> RealRangeC"""
        return _Ravl.RealRange2dC_RowRange(*args)

    def ColRange(*args):
        """ColRange(self) -> RealRangeC"""
        return _Ravl.RealRange2dC_ColRange(*args)

    def Range1(*args):
        """Range1(self) -> RealRangeC"""
        return _Ravl.RealRange2dC_Range1(*args)

    def Range2(*args):
        """Range2(self) -> RealRangeC"""
        return _Ravl.RealRange2dC_Range2(*args)

    def Involve(*args):
        """Involve(self, subrectangle)"""
        return _Ravl.RealRange2dC_Involve(*args)

    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.RealRange2dC_IsValid(*args)

    def __eq__(*args):
        """__eq__(self, oth) -> bool"""
        return _Ravl.RealRange2dC___eq__(*args)

    def __ne__(*args):
        """__ne__(self, oth) -> bool"""
        return _Ravl.RealRange2dC___ne__(*args)

    def IsOverlapping(*args):
        """IsOverlapping(self, r) -> bool"""
        return _Ravl.RealRange2dC_IsOverlapping(*args)

    __swig_destroy__ = _Ravl.delete_RealRange2dC
    __del__ = lambda self : None;
RealRange2dC_swigregister = _Ravl.RealRange2dC_swigregister
RealRange2dC_swigregister(RealRange2dC)

class PointSet2dC(DListPoint2dC):
    """Proxy of C++ PointSet2dC class"""
    __swig_setmethods__ = {}
    for _s in [DListPoint2dC]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PointSet2dC, name, value)
    __swig_getmethods__ = {}
    for _s in [DListPoint2dC]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PointSet2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> PointSet2dC"""
        this = _Ravl.new_PointSet2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Centroid(*args):
        """Centroid(self) -> Point2dC"""
        return _Ravl.PointSet2dC_Centroid(*args)

    def BoundingRectangle(*args):
        """BoundingRectangle(self) -> RealRange2dC"""
        return _Ravl.PointSet2dC_BoundingRectangle(*args)

    __swig_destroy__ = _Ravl.delete_PointSet2dC
    __del__ = lambda self : None;
PointSet2dC_swigregister = _Ravl.PointSet2dC_swigregister
PointSet2dC_swigregister(PointSet2dC)

class Polygon2dC(PointSet2dC):
    """Proxy of C++ Polygon2dC class"""
    __swig_setmethods__ = {}
    for _s in [PointSet2dC]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Polygon2dC, name, value)
    __swig_getmethods__ = {}
    for _s in [PointSet2dC]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Polygon2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> Polygon2dC"""
        this = _Ravl.new_Polygon2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def InsLast(*args):
        """InsLast(self, point)"""
        return _Ravl.Polygon2dC_InsLast(*args)

    def Size(*args):
        """Size(self) -> SizeT"""
        return _Ravl.Polygon2dC_Size(*args)

    __swig_destroy__ = _Ravl.delete_Polygon2dC
    __del__ = lambda self : None;
Polygon2dC_swigregister = _Ravl.Polygon2dC_swigregister
Polygon2dC_swigregister(Polygon2dC)

class ByteRGBArray2dC(_object):
    """Proxy of C++ ByteRGBArray2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ByteRGBArray2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ByteRGBArray2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> ByteRGBArray2dC
        __init__(self, rows, cols) -> ByteRGBArray2dC
        __init__(self, range) -> ByteRGBArray2dC
        """
        this = _Ravl.new_ByteRGBArray2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Frame(*args):
        """Frame(self) -> IndexRange2dC"""
        return _Ravl.ByteRGBArray2dC_Frame(*args)

    def Fill(*args):
        """Fill(self, value)"""
        return _Ravl.ByteRGBArray2dC_Fill(*args)

    def Stride(*args):
        """Stride(self) -> IntT"""
        return _Ravl.ByteRGBArray2dC_Stride(*args)

    def Access(*args):
        """
        Access(self, index) -> ByteRGBValueC
        Access(self, r, c) -> ByteRGBValueC
        Access(self, r, c) -> ByteRGBValueC
        """
        return _Ravl.ByteRGBArray2dC_Access(*args)

    __swig_destroy__ = _Ravl.delete_ByteRGBArray2dC
    __del__ = lambda self : None;
ByteRGBArray2dC_swigregister = _Ravl.ByteRGBArray2dC_swigregister
ByteRGBArray2dC_swigregister(ByteRGBArray2dC)

class RealRGBArray2dC(_object):
    """Proxy of C++ RealRGBArray2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RealRGBArray2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RealRGBArray2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> RealRGBArray2dC
        __init__(self, rows, cols) -> RealRGBArray2dC
        __init__(self, range) -> RealRGBArray2dC
        """
        this = _Ravl.new_RealRGBArray2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Frame(*args):
        """Frame(self) -> IndexRange2dC"""
        return _Ravl.RealRGBArray2dC_Frame(*args)

    def Fill(*args):
        """Fill(self, value)"""
        return _Ravl.RealRGBArray2dC_Fill(*args)

    def Stride(*args):
        """Stride(self) -> IntT"""
        return _Ravl.RealRGBArray2dC_Stride(*args)

    def Access(*args):
        """
        Access(self, index) -> RealRGBValueC
        Access(self, r, c) -> RealRGBValueC
        Access(self, r, c) -> RealRGBValueC
        """
        return _Ravl.RealRGBArray2dC_Access(*args)

    __swig_destroy__ = _Ravl.delete_RealRGBArray2dC
    __del__ = lambda self : None;
RealRGBArray2dC_swigregister = _Ravl.RealRGBArray2dC_swigregister
RealRGBArray2dC_swigregister(RealRGBArray2dC)

class RealRGBValueC(_object):
    """Proxy of C++ RealRGBValueC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RealRGBValueC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RealRGBValueC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, r, g, b) -> RealRGBValueC"""
        this = _Ravl.new_RealRGBValueC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Red(*args):
        """Red(self) -> RealT"""
        return _Ravl.RealRGBValueC_Red(*args)

    def Green(*args):
        """Green(self) -> RealT"""
        return _Ravl.RealRGBValueC_Green(*args)

    def Blue(*args):
        """Blue(self) -> RealT"""
        return _Ravl.RealRGBValueC_Blue(*args)

    __swig_destroy__ = _Ravl.delete_RealRGBValueC
    __del__ = lambda self : None;
RealRGBValueC_swigregister = _Ravl.RealRGBValueC_swigregister
RealRGBValueC_swigregister(RealRGBValueC)

class ByteRGBValueC(_object):
    """Proxy of C++ ByteRGBValueC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ByteRGBValueC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ByteRGBValueC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, r, g, b) -> ByteRGBValueC"""
        this = _Ravl.new_ByteRGBValueC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Red(*args):
        """Red(self) -> IntT"""
        return _Ravl.ByteRGBValueC_Red(*args)

    def Green(*args):
        """Green(self) -> IntT"""
        return _Ravl.ByteRGBValueC_Green(*args)

    def Blue(*args):
        """Blue(self) -> IntT"""
        return _Ravl.ByteRGBValueC_Blue(*args)

    __swig_destroy__ = _Ravl.delete_ByteRGBValueC
    __del__ = lambda self : None;
ByteRGBValueC_swigregister = _Ravl.ByteRGBValueC_swigregister
ByteRGBValueC_swigregister(ByteRGBValueC)

class ImageByteRGBValueC(ByteRGBArray2dC):
    """Proxy of C++ ImageByteRGBValueC class"""
    __swig_setmethods__ = {}
    for _s in [ByteRGBArray2dC]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageByteRGBValueC, name, value)
    __swig_getmethods__ = {}
    for _s in [ByteRGBArray2dC]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ImageByteRGBValueC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> ImageByteRGBValueC
        __init__(self, rows, cols) -> ImageByteRGBValueC
        __init__(self, range) -> ImageByteRGBValueC
        __init__(self, img, range) -> ImageByteRGBValueC
        """
        this = _Ravl.new_ImageByteRGBValueC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Rows(*args):
        """Rows(self) -> SizeT"""
        return _Ravl.ImageByteRGBValueC_Rows(*args)

    def Cols(*args):
        """Cols(self) -> SizeT"""
        return _Ravl.ImageByteRGBValueC_Cols(*args)

    __swig_destroy__ = _Ravl.delete_ImageByteRGBValueC
    __del__ = lambda self : None;
ImageByteRGBValueC_swigregister = _Ravl.ImageByteRGBValueC_swigregister
ImageByteRGBValueC_swigregister(ImageByteRGBValueC)

class ByteRGBImageC(ByteRGBArray2dC):
    """Proxy of C++ ByteRGBImageC class"""
    __swig_setmethods__ = {}
    for _s in [ByteRGBArray2dC]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ByteRGBImageC, name, value)
    __swig_getmethods__ = {}
    for _s in [ByteRGBArray2dC]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ByteRGBImageC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> ByteRGBImageC
        __init__(self, rows, cols) -> ByteRGBImageC
        __init__(self, range) -> ByteRGBImageC
        __init__(self, img, range) -> ByteRGBImageC
        """
        this = _Ravl.new_ByteRGBImageC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Rows(*args):
        """Rows(self) -> SizeT"""
        return _Ravl.ByteRGBImageC_Rows(*args)

    def Cols(*args):
        """Cols(self) -> SizeT"""
        return _Ravl.ByteRGBImageC_Cols(*args)

    __swig_destroy__ = _Ravl.delete_ByteRGBImageC
    __del__ = lambda self : None;
ByteRGBImageC_swigregister = _Ravl.ByteRGBImageC_swigregister
ByteRGBImageC_swigregister(ByteRGBImageC)

class ImageByteC(Array2dByteC):
    """Proxy of C++ ImageByteC class"""
    __swig_setmethods__ = {}
    for _s in [Array2dByteC]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageByteC, name, value)
    __swig_getmethods__ = {}
    for _s in [Array2dByteC]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ImageByteC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> ImageByteC
        __init__(self, rows, cols) -> ImageByteC
        __init__(self, range) -> ImageByteC
        __init__(self, img, range) -> ImageByteC
        """
        this = _Ravl.new_ImageByteC(*args)
        try: self.this.append(this)
        except: self.this = this
    def Rows(*args):
        """Rows(self) -> SizeT"""
        return _Ravl.ImageByteC_Rows(*args)

    def Cols(*args):
        """Cols(self) -> SizeT"""
        return _Ravl.ImageByteC_Cols(*args)

    __swig_destroy__ = _Ravl.delete_ImageByteC
    __del__ = lambda self : None;
ImageByteC_swigregister = _Ravl.ImageByteC_swigregister
ImageByteC_swigregister(ImageByteC)

class FontC(_object):
    """Proxy of C++ FontC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FontC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FontC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> FontC"""
        this = _Ravl.new_FontC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.FontC_IsValid(*args)

    def Center(*args):
        """Center(self, text) -> Index2dC"""
        return _Ravl.FontC_Center(*args)

    def Size(*args):
        """Size(self, text) -> Index2dC"""
        return _Ravl.FontC_Size(*args)

    def Count(*args):
        """Count(self) -> UIntT"""
        return _Ravl.FontC_Count(*args)

    __swig_destroy__ = _Ravl.delete_FontC
    __del__ = lambda self : None;
FontC_swigregister = _Ravl.FontC_swigregister
FontC_swigregister(FontC)

def Save(*args):
  """
    Save(?, ?) -> bool
    Save(?, ?) -> bool
    Save(?, ?) -> bool
    Save(?, ?) -> bool
    """
  return _Ravl.Save(*args)

def Load(*args):
  """
    Load(?, ?) -> bool
    Load(?, ?) -> bool
    Load(?, ?) -> bool
    Load(?, ?) -> bool
    """
  return _Ravl.Load(*args)

def DrawPolygon(*args):
  """
    DrawPolygon(?, ?, poly, fill=False)
    DrawPolygon(?, ?, poly)
    DrawPolygon(?, ?, poly, fill=False)
    DrawPolygon(?, ?, poly)
    """
  return _Ravl.DrawPolygon(*args)


def DefaultFont(*args):
  """DefaultFont() -> FontC"""
  return _Ravl.DefaultFont(*args)
class Affine2dC(_object):
    """Proxy of C++ Affine2dC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Affine2dC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Affine2dC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self) -> Affine2dC"""
        this = _Ravl.new_Affine2dC(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Ravl.delete_Affine2dC
    __del__ = lambda self : None;
Affine2dC_swigregister = _Ravl.Affine2dC_swigregister
Affine2dC_swigregister(Affine2dC)

def DrawText(*args):
  """
    DrawText(font, value, offset, text, image)
    DrawText(font, value, offset, text, image)
    """
  return _Ravl.DrawText(*args)

def DrawTextCenter(*args):
  """
    DrawTextCenter(font, value, offset, text, image)
    DrawTextCenter(font, value, offset, text, image)
    """
  return _Ravl.DrawTextCenter(*args)

class DateC(_object):
    """Proxy of C++ DateC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DateC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DateC, name)
    __repr__ = _swig_repr
    def NowUTC(*args):
        """NowUTC() -> DateC"""
        return _Ravl.DateC_NowUTC(*args)

    if _newclass:NowUTC = staticmethod(NowUTC)
    __swig_getmethods__["NowUTC"] = lambda x: NowUTC
    def NowLocal(*args):
        """NowLocal() -> DateC"""
        return _Ravl.DateC_NowLocal(*args)

    if _newclass:NowLocal = staticmethod(NowLocal)
    __swig_getmethods__["NowLocal"] = lambda x: NowLocal
    def NowVirtual(*args):
        """NowVirtual() -> DateC"""
        return _Ravl.DateC_NowVirtual(*args)

    if _newclass:NowVirtual = staticmethod(NowVirtual)
    __swig_getmethods__["NowVirtual"] = lambda x: NowVirtual
    def TimeZoneOffset(*args):
        """TimeZoneOffset() -> DateC"""
        return _Ravl.DateC_TimeZoneOffset(*args)

    if _newclass:TimeZoneOffset = staticmethod(TimeZoneOffset)
    __swig_getmethods__["TimeZoneOffset"] = lambda x: TimeZoneOffset
    def __init__(self, *args): 
        """
        __init__(self) -> DateC
        __init__(self, setval, useVirt=False) -> DateC
        __init__(self, setval) -> DateC
        __init__(self, val) -> DateC
        __init__(self, year, month, day, hour=0, min=0, sec=0, usec=0, useLocalTimeZone=False) -> DateC
        __init__(self, year, month, day, hour=0, min=0, sec=0, usec=0) -> DateC
        __init__(self, year, month, day, hour=0, min=0, sec=0) -> DateC
        __init__(self, year, month, day, hour=0, min=0) -> DateC
        __init__(self, year, month, day, hour=0) -> DateC
        __init__(self, year, month, day) -> DateC
        __init__(self, xsec, xusec) -> DateC
        __init__(self, val) -> DateC
        __init__(self, str) -> DateC
        """
        this = _Ravl.new_DateC(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsLeapYear(*args):
        """IsLeapYear(year) -> bool"""
        return _Ravl.DateC_IsLeapYear(*args)

    if _newclass:IsLeapYear = staticmethod(IsLeapYear)
    __swig_getmethods__["IsLeapYear"] = lambda x: IsLeapYear
    def YearToDaysSince1970(*args):
        """YearToDaysSince1970(year) -> int"""
        return _Ravl.DateC_YearToDaysSince1970(*args)

    if _newclass:YearToDaysSince1970 = staticmethod(YearToDaysSince1970)
    __swig_getmethods__["YearToDaysSince1970"] = lambda x: YearToDaysSince1970
    def IsValid(*args):
        """IsValid(self) -> bool"""
        return _Ravl.DateC_IsValid(*args)

    def IsZero(*args):
        """IsZero(self) -> bool"""
        return _Ravl.DateC_IsZero(*args)

    def SetInvalid(*args):
        """SetInvalid(self)"""
        return _Ravl.DateC_SetInvalid(*args)

    def SetToNow(*args):
        """
        SetToNow(self, useVirt=False)
        SetToNow(self)
        """
        return _Ravl.DateC_SetToNow(*args)

    def MaxUSeconds(*args):
        """MaxUSeconds(self) -> long"""
        return _Ravl.DateC_MaxUSeconds(*args)

    def Resolution(*args):
        """Resolution(self) -> long"""
        return _Ravl.DateC_Resolution(*args)

    def NormalisePos(*args):
        """NormalisePos(self)"""
        return _Ravl.DateC_NormalisePos(*args)

    def NormaliseNeg(*args):
        """NormaliseNeg(self)"""
        return _Ravl.DateC_NormaliseNeg(*args)

    def __eq__(*args):
        """__eq__(self, oth) -> bool"""
        return _Ravl.DateC___eq__(*args)

    def __ne__(*args):
        """__ne__(self, oth) -> bool"""
        return _Ravl.DateC___ne__(*args)

    def __gt__(*args):
        """__gt__(self, oth) -> bool"""
        return _Ravl.DateC___gt__(*args)

    def __lt__(*args):
        """__lt__(self, oth) -> bool"""
        return _Ravl.DateC___lt__(*args)

    def __ge__(*args):
        """__ge__(self, oth) -> bool"""
        return _Ravl.DateC___ge__(*args)

    def __le__(*args):
        """__le__(self, oth) -> bool"""
        return _Ravl.DateC___le__(*args)

    def __add__(*args):
        """__add__(self, oth) -> DateC"""
        return _Ravl.DateC___add__(*args)

    def __sub__(*args):
        """__sub__(self, oth) -> DateC"""
        return _Ravl.DateC___sub__(*args)

    def __isub__(*args):
        """
        __isub__(self, val) -> DateC
        __isub__(self, val) -> DateC
        """
        return _Ravl.DateC___isub__(*args)

    def __iadd__(*args):
        """
        __iadd__(self, val) -> DateC
        __iadd__(self, val) -> DateC
        """
        return _Ravl.DateC___iadd__(*args)

    def Text(*args):
        """Text(self) -> StringC"""
        return _Ravl.DateC_Text(*args)

    def ODBC(*args):
        """
        ODBC(self, convertUTCToLocal=False) -> StringC
        ODBC(self) -> StringC
        """
        return _Ravl.DateC_ODBC(*args)

    def SetODBC(*args):
        """SetODBC(self, odbcStr) -> bool"""
        return _Ravl.DateC_SetODBC(*args)

    def CTime(*args):
        """
        CTime(self, convertUTCToLocal=False) -> StringC
        CTime(self) -> StringC
        """
        return _Ravl.DateC_CTime(*args)

    def CTimeShort(*args):
        """
        CTimeShort(self, convertUTCToLocal=False) -> StringC
        CTimeShort(self) -> StringC
        """
        return _Ravl.DateC_CTimeShort(*args)

    def USeconds(*args):
        """USeconds(self) -> long"""
        return _Ravl.DateC_USeconds(*args)

    def TotalSeconds(*args):
        """TotalSeconds(self) -> long"""
        return _Ravl.DateC_TotalSeconds(*args)

    def Double(*args):
        """Double(self) -> double"""
        return _Ravl.DateC_Double(*args)

    def Seconds(*args):
        """
        Seconds(self, convertUTCToLocal=False) -> IntT
        Seconds(self) -> IntT
        """
        return _Ravl.DateC_Seconds(*args)

    def Minute(*args):
        """
        Minute(self, convertUTCToLocal=False) -> IntT
        Minute(self) -> IntT
        """
        return _Ravl.DateC_Minute(*args)

    def Hour(*args):
        """
        Hour(self, convertUTCToLocal=False) -> IntT
        Hour(self) -> IntT
        """
        return _Ravl.DateC_Hour(*args)

    def Month(*args):
        """
        Month(self, convertUTCToLocal=False) -> IntT
        Month(self) -> IntT
        """
        return _Ravl.DateC_Month(*args)

    def Year(*args):
        """
        Year(self, convertUTCToLocal=False) -> IntT
        Year(self) -> IntT
        """
        return _Ravl.DateC_Year(*args)

    def DayInMonth(*args):
        """
        DayInMonth(self, convertUTCToLocal=False) -> IntT
        DayInMonth(self) -> IntT
        """
        return _Ravl.DateC_DayInMonth(*args)

    def DayInYear(*args):
        """
        DayInYear(self, convertUTCToLocal=False) -> IntT
        DayInYear(self) -> IntT
        """
        return _Ravl.DateC_DayInYear(*args)

    def DayInWeek(*args):
        """
        DayInWeek(self, convertUTCToLocal=False) -> IntT
        DayInWeek(self) -> IntT
        """
        return _Ravl.DateC_DayInWeek(*args)

    def TextDayInWeek(*args):
        """
        TextDayInWeek(self, convertUTCToLocal=False) -> StringC
        TextDayInWeek(self) -> StringC
        """
        return _Ravl.DateC_TextDayInWeek(*args)

    def DaylightSaving(*args):
        """DaylightSaving(self) -> bool"""
        return _Ravl.DateC_DaylightSaving(*args)

    def Wait(*args):
        """Wait(self) -> bool"""
        return _Ravl.DateC_Wait(*args)

    __swig_destroy__ = _Ravl.delete_DateC
    __del__ = lambda self : None;
DateC_swigregister = _Ravl.DateC_swigregister
DateC_swigregister(DateC)

def DateC_NowUTC(*args):
  """DateC_NowUTC() -> DateC"""
  return _Ravl.DateC_NowUTC(*args)

def DateC_NowLocal(*args):
  """DateC_NowLocal() -> DateC"""
  return _Ravl.DateC_NowLocal(*args)

def DateC_NowVirtual(*args):
  """DateC_NowVirtual() -> DateC"""
  return _Ravl.DateC_NowVirtual(*args)

def DateC_TimeZoneOffset(*args):
  """DateC_TimeZoneOffset() -> DateC"""
  return _Ravl.DateC_TimeZoneOffset(*args)

def DateC_IsLeapYear(*args):
  """DateC_IsLeapYear(year) -> bool"""
  return _Ravl.DateC_IsLeapYear(*args)

def DateC_YearToDaysSince1970(*args):
  """DateC_YearToDaysSince1970(year) -> int"""
  return _Ravl.DateC_YearToDaysSince1970(*args)

class HashInt64Int64C(_object):
    """Proxy of C++ HashInt64Int64C class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HashInt64Int64C, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HashInt64Int64C, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, nBins=23) -> HashInt64Int64C
        __init__(self) -> HashInt64Int64C
        """
        this = _Ravl.new_HashInt64Int64C(*args)
        try: self.this.append(this)
        except: self.this = this
    def Lookup(*args):
        """Lookup(self, key, OUTPUT) -> bool"""
        return _Ravl.HashInt64Int64C_Lookup(*args)

    def Update(*args):
        """
        Update(self, key, data) -> bool
        Update(self, key) -> long long
        """
        return _Ravl.HashInt64Int64C_Update(*args)

    def Insert(*args):
        """Insert(self, key, data) -> bool"""
        return _Ravl.HashInt64Int64C_Insert(*args)

    def Access(*args):
        """
        Access(self, key, def=long long()) -> long long
        Access(self, key) -> long long
        """
        return _Ravl.HashInt64Int64C_Access(*args)

    def AccessCopy(*args):
        """
        AccessCopy(self, key, def=long long()) -> long long
        AccessCopy(self, key) -> long long
        """
        return _Ravl.HashInt64Int64C_AccessCopy(*args)

    def Del(*args):
        """
        Del(self, key, allowResize=True) -> bool
        Del(self, key) -> bool
        """
        return _Ravl.HashInt64Int64C_Del(*args)

    def Get(*args):
        """
        Get(self, key, allowResize=True) -> long long
        Get(self, key) -> long long
        """
        return _Ravl.HashInt64Int64C_Get(*args)

    def IsElm(*args):
        """IsElm(self, key) -> bool"""
        return _Ravl.HashInt64Int64C_IsElm(*args)

    def Empty(*args):
        """Empty(self)"""
        return _Ravl.HashInt64Int64C_Empty(*args)

    def Bins(*args):
        """Bins(self) -> UIntT"""
        return _Ravl.HashInt64Int64C_Bins(*args)

    def Resize(*args):
        """Resize(self, newSize)"""
        return _Ravl.HashInt64Int64C_Resize(*args)

    __swig_destroy__ = _Ravl.delete_HashInt64Int64C
    __del__ = lambda self : None;
HashInt64Int64C_swigregister = _Ravl.HashInt64Int64C_swigregister
HashInt64Int64C_swigregister(HashInt64Int64C)

class HashInt64Int64IterC(_object):
    """Proxy of C++ HashInt64Int64IterC class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HashInt64Int64IterC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HashInt64Int64IterC, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> HashInt64Int64IterC
        __init__(self, nTab) -> HashInt64Int64IterC
        __init__(self, oth) -> HashInt64Int64IterC
        """
        this = _Ravl.new_HashInt64Int64IterC(*args)
        try: self.this.append(this)
        except: self.this = this
    def First(*args):
        """First(self) -> bool"""
        return _Ravl.HashInt64Int64IterC_First(*args)

    def Next(*args):
        """Next(self) -> bool"""
        return _Ravl.HashInt64Int64IterC_Next(*args)

    def IsElm(*args):
        """IsElm(self) -> bool"""
        return _Ravl.HashInt64Int64IterC_IsElm(*args)

    def Key(*args):
        """Key(self) -> long long"""
        return _Ravl.HashInt64Int64IterC_Key(*args)

    def Data(*args):
        """
        Data(self) -> long long
        Data(self) -> long long
        """
        return _Ravl.HashInt64Int64IterC_Data(*args)

    def Del(*args):
        """Del(self) -> bool"""
        return _Ravl.HashInt64Int64IterC_Del(*args)

    __swig_destroy__ = _Ravl.delete_HashInt64Int64IterC
    __del__ = lambda self : None;
HashInt64Int64IterC_swigregister = _Ravl.HashInt64Int64IterC_swigregister
HashInt64Int64IterC_swigregister(HashInt64Int64IterC)



