#!/bin/sh
# $Id$

##################################
# Check perl
if which perl > /dev/null ; then
  true
else
  echo "Error:Can't find perl, this is required for installation & usage. "
  exit
fi

##################################
# Check make
make=""
if which make > /dev/null ; then
  if make -v 2>&1 | grep GNU > /dev/null  ; then
     MAKE=make
  fi
fi
if [ -z "${MAKE}" ] ; then
  if which gmake > /dev/null ; then 
    if gmake -v 2>&1 | grep GNU > /dev/null ; then
       MAKE=gmake
    fi
  fi
fi
if [ -z "${MAKE}" ] ; then
  echo "Error:Can't find GNU make, this is required for installation & usage. "
  exit
fi
echo "Make: ${MAKE} "

###################################
# Start installation

INSTALL_SITE="$1"
echo "Installation site '${INSTALL_SITE}'"
if mkdir -p ${INSTALL_SITE} ; then 
  true
else
  echo "Error: Can't create installation directory ${INSTALL_SITE}. " 
  exit 1
fi
ARC=`./config.arc`
if [ "${ARC}" = "unknown" ] ; then
  echo "Warning: Unknown architecture. " 
  echo "This may not work, but we'll try anyway. "
fi
echo "Architecture: '${ARC}'"

${MAKE} -f ./QMake.mk MAKEHOME=`pwd` BASE_VAR=none PROJECT_OUT=${INSTALL_SITE} PROCS=1

echo "Use the following alias for compilation.  PROJECT_OUT controls the directory "
echo "into which your own code will be compiled. The default is 'build' in your home directory. "
echo "alias mk '${MAKE} -f ${INSTALL_SITE}/share/RAVL/QMake/QMake.mk USERBUILD=1 PROJECT_OUT=$HOME/build'"
